# Generated by Django 5.1 on 2024-09-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0003_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AlterField(
            model_name='appitem',
            name='conditionratio',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='appitem',
            name='productratio',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('empty', 'empty'), ('unplaced', 'unplaced'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('complete', 'complete')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
