# Generated by Django 5.1 on 2024-09-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0005_orderitem_session_id_orderitem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('rice', 'rice'), ('drinks', 'drinks'), ('oil', 'oil')], max_length=25, null=True),
        ),
    ]
