# Generated by Django 5.1 on 2024-09-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0008_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
