# Generated by Django 5.1 on 2024-09-30 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0009_cartitem_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='session_id',
        ),
    ]
