# Generated by Django 5.1 on 2024-10-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0010_remove_orderitem_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tag',
            field=models.CharField(choices=[('in_cart', 'in_cart'), ('ordered', 'ordered')], default='in_cart', max_length=20),
        ),
    ]
